/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author cg3002624
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCentral = new javax.swing.JPanel();
        tabbedPanelCentral = new javax.swing.JTabbedPane();
        panelSobre = new javax.swing.JPanel();
        panelSobreCentral = new javax.swing.JPanel();
        scrollSobre = new javax.swing.JScrollPane();
        textSobre = new javax.swing.JTextArea();
        panelSobreSuperior = new javax.swing.JPanel();
        panelSobreInferior = new javax.swing.JPanel();
        panelSobreDireita = new javax.swing.JPanel();
        panelSobreEsquerda = new javax.swing.JPanel();
        panelTermos = new javax.swing.JPanel();
        panelEquipe = new javax.swing.JPanel();
        panelContato = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelInferior = new javax.swing.JPanel();
        panelDireita = new javax.swing.JPanel();
        panelEsquerda = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCentral.setForeground(new java.awt.Color(0, 153, 153));
        panelCentral.setLayout(new java.awt.BorderLayout());

        panelSobre.setLayout(new java.awt.BorderLayout());

        panelSobreCentral.setBackground(new java.awt.Color(255, 255, 153));
        panelSobreCentral.setLayout(new java.awt.BorderLayout());

        textSobre.setColumns(20);
        textSobre.setRows(5);
        scrollSobre.setViewportView(textSobre);

        panelSobreCentral.add(scrollSobre, java.awt.BorderLayout.CENTER);

        panelSobre.add(panelSobreCentral, java.awt.BorderLayout.CENTER);

        panelSobreSuperior.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout panelSobreSuperiorLayout = new javax.swing.GroupLayout(panelSobreSuperior);
        panelSobreSuperior.setLayout(panelSobreSuperiorLayout);
        panelSobreSuperiorLayout.setHorizontalGroup(
            panelSobreSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        panelSobreSuperiorLayout.setVerticalGroup(
            panelSobreSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelSobre.add(panelSobreSuperior, java.awt.BorderLayout.PAGE_START);

        panelSobreInferior.setPreferredSize(new java.awt.Dimension(637, 50));

        javax.swing.GroupLayout panelSobreInferiorLayout = new javax.swing.GroupLayout(panelSobreInferior);
        panelSobreInferior.setLayout(panelSobreInferiorLayout);
        panelSobreInferiorLayout.setHorizontalGroup(
            panelSobreInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        panelSobreInferiorLayout.setVerticalGroup(
            panelSobreInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelSobre.add(panelSobreInferior, java.awt.BorderLayout.PAGE_END);

        panelSobreDireita.setPreferredSize(new java.awt.Dimension(20, 26));

        javax.swing.GroupLayout panelSobreDireitaLayout = new javax.swing.GroupLayout(panelSobreDireita);
        panelSobreDireita.setLayout(panelSobreDireitaLayout);
        panelSobreDireitaLayout.setHorizontalGroup(
            panelSobreDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelSobreDireitaLayout.setVerticalGroup(
            panelSobreDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        panelSobre.add(panelSobreDireita, java.awt.BorderLayout.LINE_END);

        panelSobreEsquerda.setMaximumSize(new java.awt.Dimension(32767, 10));
        panelSobreEsquerda.setPreferredSize(new java.awt.Dimension(20, 26));

        javax.swing.GroupLayout panelSobreEsquerdaLayout = new javax.swing.GroupLayout(panelSobreEsquerda);
        panelSobreEsquerda.setLayout(panelSobreEsquerdaLayout);
        panelSobreEsquerdaLayout.setHorizontalGroup(
            panelSobreEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelSobreEsquerdaLayout.setVerticalGroup(
            panelSobreEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        panelSobre.add(panelSobreEsquerda, java.awt.BorderLayout.LINE_START);

        tabbedPanelCentral.addTab("Sobre", panelSobre);

        javax.swing.GroupLayout panelTermosLayout = new javax.swing.GroupLayout(panelTermos);
        panelTermos.setLayout(panelTermosLayout);
        panelTermosLayout.setHorizontalGroup(
            panelTermosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        panelTermosLayout.setVerticalGroup(
            panelTermosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        tabbedPanelCentral.addTab("Termos de Serviço", panelTermos);

        javax.swing.GroupLayout panelEquipeLayout = new javax.swing.GroupLayout(panelEquipe);
        panelEquipe.setLayout(panelEquipeLayout);
        panelEquipeLayout.setHorizontalGroup(
            panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        panelEquipeLayout.setVerticalGroup(
            panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        tabbedPanelCentral.addTab("Equipe", panelEquipe);

        javax.swing.GroupLayout panelContatoLayout = new javax.swing.GroupLayout(panelContato);
        panelContato.setLayout(panelContatoLayout);
        panelContatoLayout.setHorizontalGroup(
            panelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        panelContatoLayout.setVerticalGroup(
            panelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        tabbedPanelCentral.addTab("Contato", panelContato);

        panelCentral.add(tabbedPanelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(panelInferior, java.awt.BorderLayout.PAGE_END);

        panelDireita.setPreferredSize(new java.awt.Dimension(20, 254));

        javax.swing.GroupLayout panelDireitaLayout = new javax.swing.GroupLayout(panelDireita);
        panelDireita.setLayout(panelDireitaLayout);
        panelDireitaLayout.setHorizontalGroup(
            panelDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelDireitaLayout.setVerticalGroup(
            panelDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        getContentPane().add(panelDireita, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout panelEsquerdaLayout = new javax.swing.GroupLayout(panelEsquerda);
        panelEsquerda.setLayout(panelEsquerdaLayout);
        panelEsquerdaLayout.setHorizontalGroup(
            panelEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelEsquerdaLayout.setVerticalGroup(
            panelEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        getContentPane().add(panelEsquerda, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelContato;
    private javax.swing.JPanel panelDireita;
    private javax.swing.JPanel panelEquipe;
    private javax.swing.JPanel panelEsquerda;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSobre;
    private javax.swing.JPanel panelSobreCentral;
    private javax.swing.JPanel panelSobreDireita;
    private javax.swing.JPanel panelSobreEsquerda;
    private javax.swing.JPanel panelSobreInferior;
    private javax.swing.JPanel panelSobreSuperior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTermos;
    private javax.swing.JScrollPane scrollSobre;
    private javax.swing.JTabbedPane tabbedPanelCentral;
    private javax.swing.JTextArea textSobre;
    // End of variables declaration//GEN-END:variables
}
